
--[[ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING, CHECK "config.lua" FOR THE CONFIG ]]
--[[ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING, CHECK "config.lua" FOR THE CONFIG ]]
--[[ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING, CHECK "config.lua" FOR THE CONFIG ]]

function applyConfig(config)
    -- Retrieving the player ped and veh
    local ped = GetPlayerPed(-1)
    local veh = GetVehiclePedIsIn(ped, false)

    -- Checking if the ped is alive/exists
    if (not DoesEntityExist(ped)) or IsEntityDead(ped) then
        TriggerEvent('chatMessage', '', {255,255,255}, "It seems that we can't do that!")
        return
    end

    -- Setting the player's model
    if config.skin ~= nil then
        local model = GetHashKey(config.skin)
        RequestModel(model)
        while not HasModelLoaded(model) do
            Wait(0)
        end
        SetPlayerModel(PlayerId(), model)
        SetModelAsNoLongerNeeded(model)
    end

    ped = GetPlayerPed(-1)

    -- Setting the player's guns
    RemoveAllPedWeapons(ped, 0)
    Wait(10)
    for _, value in ipairs(config.guns) do
        GiveWeaponToPed(ped, GetHashKey(value), 9999, false, false)
    end

    -- Setting the player's guns' attachements
    for _, value in ipairs(config.attachements) do
        local gun = value.gun
        for _, v in ipairs(value.ids) do
            GiveWeaponComponentToPed(ped, GetHashKey(gun), GetHashKey(v))
        end
    end

    if DoesEntityExist(veh) then
        TaskEnterVehicle(ped, veh, 1000, -1, 1.0, 16, 0)
    end
end

RegisterNetEvent('gungiver:apply')

AddEventHandler('gungiver:apply', function(config)
    applyConfig(config)
end)
