
--[[ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING, CHECK "config.lua" FOR THE CONFIG ]]
--[[ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING, CHECK "config.lua" FOR THE CONFIG ]]
--[[ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING, CHECK "config.lua" FOR THE CONFIG ]]

local function callClient(source, config)
    TriggerClientEvent('gungiver:apply', source, config)
end

AddEventHandler('chatMessage', function(source, n, msg)
    local cfg = config[string.lower(msg)]

    if cfg ~= nil then
        callClient(source, cfg)

        CancelEvent()
    end
end)

RegisterServerEvent('gungiver:callclient')
AddEventHandler('gungiver:callclient', function(source, configname)
    local cfg = config[string.lower(configname)]

    if cfg ~= nil then
        callClient(source, cfg)
    end
end)